# Generated by Django 5.2.16 on 2026-09-27 05:55

import django.core.validators
import employees.services
import employees.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_seed_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text='JPG, PNG o WebP de máximo 5 MB', null=True, upload_to=employees.services.EmployeePhotoPath(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), employees.validators.EmployeePhotoValidator()], verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='photo',
            field=models.TextField(blank=True, help_text='JPG, PNG o WebP de máximo 5 MB', max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), employees.validators.EmployeePhotoValidator()], verbose_name='Foto'),
        ),
    ]
