# Generated by Django 5.2.16 on 2026-10-01 20:31

from django.db import migrations, models


# the old option merged two groups, so its rows cannot be told apart: they are left empty
# for Talent Management to fill in again
def clear_merged_ethnicity(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    Employee.objects.filter(ethnicity='indigenous_roma').update(ethnicity='')


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_photo'),
    ]

    operations = [
        migrations.RunPython(clear_merged_ethnicity, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='employee',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('indigenous', 'Indígena'), ('roma', 'Gitano(a) / Rrom'), ('raizal', 'Raizal del Archipiélago de San Andrés, Providencia y Santa Catalina'), ('palenquero', 'Palenquero(a) de San Basilio'), ('afro_colombian', 'Negro(a), mulato(a), afrodescendiente o afrocolombiano(a)'), ('none', 'Ningún grupo étnico'), ('undisclosed', 'No informa / Prefiere no responder')], max_length=30, verbose_name='Pertenencia étnica'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('indigenous', 'Indígena'), ('roma', 'Gitano(a) / Rrom'), ('raizal', 'Raizal del Archipiélago de San Andrés, Providencia y Santa Catalina'), ('palenquero', 'Palenquero(a) de San Basilio'), ('afro_colombian', 'Negro(a), mulato(a), afrodescendiente o afrocolombiano(a)'), ('none', 'Ningún grupo étnico'), ('undisclosed', 'No informa / Prefiere no responder')], max_length=30, verbose_name='Pertenencia étnica'),
        ),
    ]
