# Generated by Django 5.2.16 on 2026-10-01 20:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_split_indigenous_and_roma'),
        ('users', '0005_seed_divisions_and_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='training',
            field=models.TextField(blank=True, help_text='AROs y formaciones, en texto libre', verbose_name='Formación'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='training',
            field=models.TextField(blank=True, help_text='AROs y formaciones, en texto libre', verbose_name='Formación'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='additional_role',
            field=models.CharField(choices=[('none', 'Ninguno'), ('brigadier', 'Brigadista'), ('coexistence_committee', 'Comité de Convivencia'), ('copasst', 'COPASST'), ('forklift_operator', 'Op. Montacargas')], max_length=30, verbose_name='Rol adicional'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Dirección de residencia'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='area',
            field=models.CharField(choices=[('ADMON-51', 'ADMON-51'), ('CIF-73', 'CIF -73'), ('LOG-52', 'LOG-52'), ('MOD-72', 'MOD-72'), ('VENTAS-52', 'VENTAS-52')], max_length=20, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_municipality',
            field=models.CharField(max_length=120, verbose_name='Municipio de nacimiento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='blood_type',
            field=models.CharField(choices=[('a_positive', 'A+'), ('a_negative', 'A-'), ('b_positive', 'B+'), ('b_negative', 'B-'), ('ab_positive', 'AB+'), ('ab_negative', 'AB-'), ('o_positive', 'O+'), ('o_negative', 'O-')], max_length=15, verbose_name='Grupo sanguíneo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(choices=[('administrative', 'Administrativos'), ('production_apprentice', 'AprProd'), ('production_apprentice_ad', 'AprProd-Ad'), ('commercial', 'Comerciales'), ('operative_supply', 'Operativo-Abastecimiento'), ('operative_administrative', 'Operativo-Administrativos'), ('operative_manufacturing', 'Operativo-Manufactura'), ('operative_technical', 'Operativo-Procesos Técnicos')], max_length=30, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(max_length=120, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='collective_agreement',
            field=models.BooleanField(verbose_name='Pacto colectivo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('fixed_three_months', 'Fijo 3 meses'), ('fixed_six_months', 'Fijo 6 meses'), ('fixed_special', 'Fijo Especial'), ('fixed_one_year', 'Fijo un año'), ('indefinite', 'Indefinido'), ('work_and_labor', 'Obra y Labor')], max_length=30, verbose_name='Tipo de contrato'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cost_center',
            field=models.CharField(choices=[('PCOFB20000', 'PCOFB20000'), ('PCOFB20114', 'PCOFB20114'), ('PCOFB20300', 'PCOFB20300'), ('PCOFB30200', 'PCOFB30200'), ('PCOFB30201', 'PCOFB30201'), ('PCOFB30202', 'PCOFB30202'), ('PCOFB30203', 'PCOFB30203'), ('PCOFB30205', 'PCOFB30205'), ('PCOFB30206', 'PCOFB30206'), ('PCOFB30207', 'PCOFB30207'), ('PCOFB30208', 'PCOFB30208'), ('PCOFB30209', 'PCOFB30209'), ('PCOFB30300', 'PCOFB30300'), ('PCOFB30500', 'PCOFB30500'), ('PCOFB30503', 'PCOFB30503'), ('PCOFB30601', 'PCOFB30601'), ('PCOFB40100', 'PCOFB40100'), ('PCOFB40400', 'PCOFB40400'), ('PCOFB50103', 'PCOFB50103'), ('PCOFB50302', 'PCOFB50302'), ('PCOFB50400', 'PCOFB50400')], max_length=20, verbose_name='Centro de costos'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='current_salary',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Salario actual'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dependents_count',
            field=models.PositiveSmallIntegerField(verbose_name='Número de personas a cargo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education_level',
            field=models.CharField(choices=[('primary_complete', 'Primaria Completa'), ('primary_incomplete', 'Primaria Incompleta'), ('high_school_complete', 'Bachillerato Completo'), ('high_school_incomplete', 'Bachillerato Incompleto'), ('technical_complete', 'Técnico Completo'), ('technologist_complete', 'Tecnológico Completo'), ('technical_incomplete', 'Técnico / Tecnológico Incompleto'), ('professional_complete', 'Profesional Completo'), ('professional_incomplete', 'Profesional Incompleto'), ('postgraduate', 'Especialización / Postgrado'), ('masters', 'Maestría')], max_length=30, verbose_name='Nivel educativo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('direct', 'Directa'), ('temporary_ad', 'Temporal-Ad'), ('temporary_sai', 'Temporal-Sai')], max_length=20, verbose_name='Tipo de vinculación'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ethnicity',
            field=models.CharField(choices=[('indigenous', 'Indígena'), ('roma', 'Gitano(a) / Rrom'), ('raizal', 'Raizal del Archipiélago de San Andrés, Providencia y Santa Catalina'), ('palenquero', 'Palenquero(a) de San Basilio'), ('afro_colombian', 'Negro(a), mulato(a), afrodescendiente o afrocolombiano(a)'), ('none', 'Ningún grupo étnico'), ('undisclosed', 'No informa / Prefiere no responder')], max_length=30, verbose_name='Pertenencia étnica'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='evaluation_group',
            field=models.CharField(choices=[('operative', 'Operativo'), ('analyst', 'Analista / Auxiliar'), ('commercial', 'Comercial'), ('leader', 'Líder / Coordinador'), ('director', 'Director')], max_length=20, verbose_name='Grupo de evaluación'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='family_composition',
            field=models.CharField(choices=[('lives_alone', 'Vive solo'), ('with_partner', 'Vive con pareja'), ('with_children', 'Vive con hijos'), ('with_parents', 'Vive con padres'), ('with_other_relatives', 'Vive con otros familiares'), ('with_non_relatives', 'Vive con personas no familiares'), ('other', 'Otro')], max_length=30, verbose_name='Composición familiar'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='has_children',
            field=models.BooleanField(verbose_name='Tiene hijos'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='health_insurer',
            field=models.CharField(choices=[('adres', 'Adres - Fosyga'), ('coosalud', 'Coosalud'), ('compensar', 'Compensar'), ('nueva_eps', 'Nueva EPS'), ('salud_total', 'Salud Total EPS'), ('sanitas', 'Sanitas'), ('savia_salud', 'Savia Salud EPS'), ('sura', 'Sura EPS')], max_length=30, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_leader',
            field=models.BooleanField(help_text='Con cargo de liderazgo o personal a cargo. No da acceso al sistema', verbose_name='Es líder'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Soltero'), ('married', 'Casado'), ('common_law', 'Unión libre'), ('separated', 'Separado/divorciado'), ('widowed', 'Viudo')], max_length=20, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'El celular solo lleva números.')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(max_length=120, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='neighborhood',
            field=models.CharField(max_length=120, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='occupational_risk_insurer',
            field=models.CharField(choices=[('sura', 'SURA'), ('seguros_bolivar', 'SEGUROS BOLIVAR')], max_length=30, verbose_name='ARL'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_employees', to='employees.position', verbose_name='Cargo actual'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_start_date',
            field=models.DateField(verbose_name='Fecha de inicio del cargo actual'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_type',
            field=models.CharField(choices=[('basic', 'Básico'), ('apprentice_support', 'Apoyo Sostenimiento'), ('integral', 'Integral')], max_length=30, verbose_name='Tipo de salario'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='users.section', verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('female', 'Femenino'), ('male', 'Masculino')], max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='socioeconomic_stratum',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], verbose_name='Estrato socioeconómico'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='additional_role',
            field=models.CharField(choices=[('none', 'Ninguno'), ('brigadier', 'Brigadista'), ('coexistence_committee', 'Comité de Convivencia'), ('copasst', 'COPASST'), ('forklift_operator', 'Op. Montacargas')], max_length=30, verbose_name='Rol adicional'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Dirección de residencia'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='area',
            field=models.CharField(choices=[('ADMON-51', 'ADMON-51'), ('CIF-73', 'CIF -73'), ('LOG-52', 'LOG-52'), ('MOD-72', 'MOD-72'), ('VENTAS-52', 'VENTAS-52')], max_length=20, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='birth_date',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='birth_municipality',
            field=models.CharField(max_length=120, verbose_name='Municipio de nacimiento'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='blood_type',
            field=models.CharField(choices=[('a_positive', 'A+'), ('a_negative', 'A-'), ('b_positive', 'B+'), ('b_negative', 'B-'), ('ab_positive', 'AB+'), ('ab_negative', 'AB-'), ('o_positive', 'O+'), ('o_negative', 'O-')], max_length=15, verbose_name='Grupo sanguíneo'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='category',
            field=models.CharField(choices=[('administrative', 'Administrativos'), ('production_apprentice', 'AprProd'), ('production_apprentice_ad', 'AprProd-Ad'), ('commercial', 'Comerciales'), ('operative_supply', 'Operativo-Abastecimiento'), ('operative_administrative', 'Operativo-Administrativos'), ('operative_manufacturing', 'Operativo-Manufactura'), ('operative_technical', 'Operativo-Procesos Técnicos')], max_length=30, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='city',
            field=models.CharField(max_length=120, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='collective_agreement',
            field=models.BooleanField(verbose_name='Pacto colectivo'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='contract_type',
            field=models.CharField(choices=[('fixed_three_months', 'Fijo 3 meses'), ('fixed_six_months', 'Fijo 6 meses'), ('fixed_special', 'Fijo Especial'), ('fixed_one_year', 'Fijo un año'), ('indefinite', 'Indefinido'), ('work_and_labor', 'Obra y Labor')], max_length=30, verbose_name='Tipo de contrato'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='cost_center',
            field=models.CharField(choices=[('PCOFB20000', 'PCOFB20000'), ('PCOFB20114', 'PCOFB20114'), ('PCOFB20300', 'PCOFB20300'), ('PCOFB30200', 'PCOFB30200'), ('PCOFB30201', 'PCOFB30201'), ('PCOFB30202', 'PCOFB30202'), ('PCOFB30203', 'PCOFB30203'), ('PCOFB30205', 'PCOFB30205'), ('PCOFB30206', 'PCOFB30206'), ('PCOFB30207', 'PCOFB30207'), ('PCOFB30208', 'PCOFB30208'), ('PCOFB30209', 'PCOFB30209'), ('PCOFB30300', 'PCOFB30300'), ('PCOFB30500', 'PCOFB30500'), ('PCOFB30503', 'PCOFB30503'), ('PCOFB30601', 'PCOFB30601'), ('PCOFB40100', 'PCOFB40100'), ('PCOFB40400', 'PCOFB40400'), ('PCOFB50103', 'PCOFB50103'), ('PCOFB50302', 'PCOFB50302'), ('PCOFB50400', 'PCOFB50400')], max_length=20, verbose_name='Centro de costos'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='current_salary',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Salario actual'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='dependents_count',
            field=models.PositiveSmallIntegerField(verbose_name='Número de personas a cargo'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='education_level',
            field=models.CharField(choices=[('primary_complete', 'Primaria Completa'), ('primary_incomplete', 'Primaria Incompleta'), ('high_school_complete', 'Bachillerato Completo'), ('high_school_incomplete', 'Bachillerato Incompleto'), ('technical_complete', 'Técnico Completo'), ('technologist_complete', 'Tecnológico Completo'), ('technical_incomplete', 'Técnico / Tecnológico Incompleto'), ('professional_complete', 'Profesional Completo'), ('professional_incomplete', 'Profesional Incompleto'), ('postgraduate', 'Especialización / Postgrado'), ('masters', 'Maestría')], max_length=30, verbose_name='Nivel educativo'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='employment_type',
            field=models.CharField(choices=[('direct', 'Directa'), ('temporary_ad', 'Temporal-Ad'), ('temporary_sai', 'Temporal-Sai')], max_length=20, verbose_name='Tipo de vinculación'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='ethnicity',
            field=models.CharField(choices=[('indigenous', 'Indígena'), ('roma', 'Gitano(a) / Rrom'), ('raizal', 'Raizal del Archipiélago de San Andrés, Providencia y Santa Catalina'), ('palenquero', 'Palenquero(a) de San Basilio'), ('afro_colombian', 'Negro(a), mulato(a), afrodescendiente o afrocolombiano(a)'), ('none', 'Ningún grupo étnico'), ('undisclosed', 'No informa / Prefiere no responder')], max_length=30, verbose_name='Pertenencia étnica'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='evaluation_group',
            field=models.CharField(choices=[('operative', 'Operativo'), ('analyst', 'Analista / Auxiliar'), ('commercial', 'Comercial'), ('leader', 'Líder / Coordinador'), ('director', 'Director')], max_length=20, verbose_name='Grupo de evaluación'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='family_composition',
            field=models.CharField(choices=[('lives_alone', 'Vive solo'), ('with_partner', 'Vive con pareja'), ('with_children', 'Vive con hijos'), ('with_parents', 'Vive con padres'), ('with_other_relatives', 'Vive con otros familiares'), ('with_non_relatives', 'Vive con personas no familiares'), ('other', 'Otro')], max_length=30, verbose_name='Composición familiar'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='has_children',
            field=models.BooleanField(verbose_name='Tiene hijos'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='health_insurer',
            field=models.CharField(choices=[('adres', 'Adres - Fosyga'), ('coosalud', 'Coosalud'), ('compensar', 'Compensar'), ('nueva_eps', 'Nueva EPS'), ('salud_total', 'Salud Total EPS'), ('sanitas', 'Sanitas'), ('savia_salud', 'Savia Salud EPS'), ('sura', 'Sura EPS')], max_length=30, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='hire_date',
            field=models.DateField(verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='is_leader',
            field=models.BooleanField(help_text='Con cargo de liderazgo o personal a cargo. No da acceso al sistema', verbose_name='Es líder'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Soltero'), ('married', 'Casado'), ('common_law', 'Unión libre'), ('separated', 'Separado/divorciado'), ('widowed', 'Viudo')], max_length=20, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='mobile_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'El celular solo lleva números.')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='nationality',
            field=models.CharField(max_length=120, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='neighborhood',
            field=models.CharField(max_length=120, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='occupational_risk_insurer',
            field=models.CharField(choices=[('sura', 'SURA'), ('seguros_bolivar', 'SEGUROS BOLIVAR')], max_length=30, verbose_name='ARL'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='position_start_date',
            field=models.DateField(verbose_name='Fecha de inicio del cargo actual'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='salary_type',
            field=models.CharField(choices=[('basic', 'Básico'), ('apprentice_support', 'Apoyo Sostenimiento'), ('integral', 'Integral')], max_length=30, verbose_name='Tipo de salario'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='sex',
            field=models.CharField(choices=[('female', 'Femenino'), ('male', 'Masculino')], max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='socioeconomic_stratum',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], verbose_name='Estrato socioeconómico'),
        ),
    ]
