# Generated by Django 5.2.16 on 2026-10-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_cost_center_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='retirement_date',
            field=models.DateField(blank=True, help_text='Obligatoria si el empleado está retirado; se borra al volver a Activo', null=True, verbose_name='Fecha de retiro'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='retirement_date',
            field=models.DateField(blank=True, help_text='Obligatoria si el empleado está retirado; se borra al volver a Activo', null=True, verbose_name='Fecha de retiro'),
        ),
    ]
