# Generated by Django 5.2.16 on 2026-10-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_retirement_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAlertDispatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_on', models.DateField(help_text='Un registro por día: evita que el correo salga dos veces', unique=True, verbose_name='Fecha')),
                ('recipients', models.TextField(verbose_name='Destinatarios')),
                ('employee_count', models.PositiveIntegerField(verbose_name='Empleados en alerta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Envío de vencimientos',
                'verbose_name_plural': 'Envíos de vencimientos',
                'ordering': ['-sent_on'],
            },
        ),
    ]
