# Generated by Django 5.2.16 on 2026-10-07 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_contract_alert_dispatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExportLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_format', models.CharField(max_length=10, verbose_name='Formato')),
                ('title', models.CharField(max_length=200, verbose_name='Reporte')),
                ('filters', models.JSONField(default=dict, verbose_name='Filtros')),
                ('fields', models.JSONField(default=list, verbose_name='Campos')),
                ('row_count', models.PositiveIntegerField(verbose_name='Filas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_exports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Descarga de empleados',
                'verbose_name_plural': 'Descargas de empleados',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
