# Generated by Django 5.2.16 on 2026-10-07 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_export_log'),
        ('users', '0006_create_cache_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cut_date', models.DateField(help_text='Último día del mes que conserva', unique=True, verbose_name='Fecha de corte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tomado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última vez rehecho')),
                ('taken_by', models.ForeignKey(blank=True, help_text='Vacío cuando lo tomó la tarea programada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_cuts', to=settings.AUTH_USER_MODEL, verbose_name='Tomado por')),
            ],
            options={
                'verbose_name': 'Corte mensual',
                'verbose_name_plural': 'Cortes mensuales',
                'ordering': ['-cut_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='Apellidos y nombres')),
                ('id_number', models.PositiveBigIntegerField(verbose_name='Identificación')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('retired', 'Retirado')], max_length=20, verbose_name='Estado')),
                ('data', models.JSONField(help_text='Todas las columnas del empleado a la fecha de corte; el perfil se aplica al leer', verbose_name='Datos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_snapshots', to='users.division', verbose_name='Dirección')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='employees.employee', verbose_name='Empleado')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_snapshots', to='users.section', verbose_name='Sección')),
                ('cut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='employees.monthlycut', verbose_name='Corte')),
            ],
            options={
                'verbose_name': 'Empleado en un corte',
                'verbose_name_plural': 'Empleados en cortes',
                'ordering': ['full_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('cut', 'employee'), name='employees_employeesnapshot_unique')],
            },
        ),
    ]
