# Generated by Django 5.2.16 on 2026-10-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_monthly_cuts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeExportLog',
        ),
    ]
