# Generated by Django 5.2.16 on 2026-09-08 05:24

import users.managers.UserManager
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_department_division_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.managers.UserManager.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Es el identificador de acceso al sistema', max_length=254, unique=True, validators=[users.validators.CorporateEmailValidator()], verbose_name='Correo corporativo'),
        ),
    ]
