# Generated by Django 5.2.16 on 2026-09-27 00:16

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='division',
            name='code',
        ),
        migrations.RemoveField(
            model_name='division',
            name='has_full_employee_access',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, choices=[('talent_management', 'Talento Humano'), ('general_management', 'Gerencia General'), ('occupational_safety', 'SST - SGI'), ('director', 'Director'), ('leader', 'Líder')], default='', help_text='Decide qué empleados y qué datos ve. Vacío solo para cuentas de TI', max_length=30, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='division',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Obligatoria para el perfil Director', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.division', verbose_name='Dirección'),
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('email', models.EmailField(db_index=True, help_text='Es el identificador de acceso al sistema', max_length=254, validators=[users.validators.CorporateEmailValidator()], verbose_name='Correo corporativo')),
                ('profile', models.CharField(blank=True, choices=[('talent_management', 'Talento Humano'), ('general_management', 'Gerencia General'), ('occupational_safety', 'SST - SGI'), ('director', 'Director'), ('leader', 'Líder')], default='', help_text='Decide qué empleados y qué datos ve. Vacío solo para cuentas de TI', max_length=30, verbose_name='Perfil')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('division', models.ForeignKey(blank=True, db_constraint=False, help_text='Obligatoria para el perfil Director', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.division', verbose_name='Dirección')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Usuario',
                'verbose_name_plural': 'historical Usuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUserSection',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('section', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.section', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'historical Sección a cargo',
                'verbose_name_plural': 'historical Secciones a cargo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UserSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='users.section', verbose_name='Sección')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sección a cargo',
                'verbose_name_plural': 'Secciones a cargo',
                'ordering': ['user', 'section'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.UserSection', to='users.section', verbose_name='Secciones a cargo'),
        ),
        migrations.AddConstraint(
            model_name='usersection',
            constraint=models.UniqueConstraint(fields=('user', 'section'), name='users_usersection_unique'),
        ),
    ]
